name: CDK

on:
  pull_request:
    paths:
      - 'cdk/**'
    branches:
      - '!master'
      - '*'

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 'current'
        check-latest: true

    - run: npm install
    - run: npm install -g aws-cdk

    - name: Install aws-cli
      run: sudo apt-get install awscli

    - name: Install Python
      run: sudo apt install python3.9

    - name: Install Python Dependencies
      working-directory: cdk
      run: pip3 install -r requirements.txt

    - name: Set Environment Credentials and Synth
      working-directory: cdk
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: cdk synth
